# Generated by Django 2.1.3 on 2019-01-27 08:55

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('About_name', models.CharField(max_length=255, null=True, verbose_name='标题')),
                ('About_content', tinymce.models.HTMLField(null=True, verbose_name='正文')),
                ('Create_time', models.DateTimeField(auto_now_add=True)),
                ('Last_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'blog_about',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_name', models.CharField(max_length=20, verbose_name='用户名')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('address', models.CharField(max_length=100, verbose_name='联系地址')),
                ('message', models.CharField(max_length=200, verbose_name='留言信息')),
                ('Create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'blog_message',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Note_name', models.CharField(max_length=255, verbose_name='标题')),
                ('Note_author', models.CharField(max_length=20, verbose_name='作者')),
                ('Note_summary', models.CharField(max_length=255, null=True, verbose_name='概述')),
                ('Note_content', tinymce.models.HTMLField(verbose_name='正文')),
                ('Note_scr', models.CharField(max_length=255, null=True, verbose_name='图片地址')),
                ('Note_href', models.CharField(max_length=255, null=True, verbose_name='Blog地址')),
                ('Create_time', models.DateTimeField(auto_now_add=True)),
                ('Last_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'blog_note',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=128, unique=True, verbose_name='用户名')),
                ('Password', models.CharField(max_length=256, verbose_name='密码')),
                ('Email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱')),
                ('Gender', models.BooleanField(default=True, verbose_name='性别')),
                ('Create_time', models.DateTimeField(auto_now_add=True)),
                ('Last_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'blog_user',
                'ordering': ['id'],
            },
        ),
    ]
