# Generated by Django 2.1.3 on 2019-01-27 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogAPP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='User_head',
            field=models.CharField(default='/static/images/h.jpg', max_length=256, verbose_name='头像地址'),
        ),
    ]
